apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
spec:
  replicas: 4
  revisionHistoryLimit: 8
  selector:
    matchLabels:
      app: rollout-bluegreen2
  template:
    metadata:
      labels:
        app: rollout-bluegreen2
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: rollout-bluegreen2-active
      previewService: rollout-bluegreen2-preview
      autoPromotionEnabled: false