apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  annotations:
    argocd-image-updater.argoproj.io/image-list: vsv21gml/nginx
    argocd-image-updater.argoproj.io/org_app.update-strategy: latest
spec:
  replicas: 7
  selector:
    matchLabels:
      run: mynginx
  template:
    metadata:
      labels:
        run: mynginx
    spec:
      containers:
      - image: vsv21gml/nginx:0.0.1
        name: mynginx
        ports:
        - containerPort: 80