apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 7
  selector:
    matchLabels:
      run: mynginx
  template:
    metadata:
      labels:
        run: mynginx
    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        name: mynginx
        ports:
        - containerPort: 80