apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  annotations:
    argocd-image-updater.argoproj.io/image-list: opensearch:vsv21gml/opensearch:latest
    argocd-image-updater.argoproj.io/opensearch.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/opensearch.update-strategy: digest
spec:
  destination:
    name: ''
    namespace: opensearch
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://opensearch-project.github.io/helm-charts'
    targetRevision: 2.14.1
    chart: opensearch
    helm:
      valueFiles:
        - values.yaml
      values: |-
        image:
          repository: "vsv21gml/opensearch"
          tag: "latest"
          pullPolicy: "Always"
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true